#ifndef _MAIN_H_
#define _MAIN_H_

//  BEGIN VERSION
#define BOOTLOADER_VERSION_NAME     "v3bl-"
#define BOOTLOADER_VERSION_MAJOR    1
#define BOOTLOADER_VERSION_MINOR    0
#define BOOTLOADER_VERSION_PATCH    0
//  * Numbers can ONLY BE ONE DIGIT!!!
//  * Do not remove "BEGIN VERSION", it is used by make_kflash.py

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define ARR_SIZE(x) sizeof(x)/sizeof(x[0])

//  Magic Bytes
#define FD_HDR_MAGIC_0      'K'
#define FD_HDR_MAGIC_1      'M'
#define FD_HDR_MAGIC_2      'X'
#define FD_HDR_VER          0x01

#define BOOTLOADER_STRING           BOOTLOADER_VERSION_NAME TOSTRING(BOOTLOADER_VERSION_MAJOR) "." TOSTRING(BOOTLOADER_VERSION_MINOR) "." TOSTRING(BOOTLOADER_VERSION_PATCH)

#define CPU_FREQUENCY 48000000

#define FLASH_WAIT_STATES 1

#ifndef BOOT_USART_MODULE
#define BOOT_USART_MODULE SERCOM3
#define BOOT_USART_PAD_SETTINGS UART_RX_PAD1_TX_PAD0
#define BOOT_USART_PAD3 PINMUX_UNUSED
#define BOOT_USART_PAD2 PINMUX_UNUSED
#define BOOT_USART_PAD1 PINMUX_PA23C_SERCOM3_PAD1
#define BOOT_USART_PAD0 PINMUX_PA22C_SERCOM3_PAD0
#endif

#endif // _MAIN_H_
